### PR TITLE
Develop 2

### PR DESCRIPTION
**Pull request by keomabrun**
This is an example of the logging module. Logging is configured with a very simply line in `ServerGateway.py`. Then, each module can `import logging` and `logging.debug()` or other logging levels.
All the logs will be written in `dweb_gateway.log` with the same line header: 
`<LOGLEVEL>:root:<MESSAGE>`. Ex: `DEBUG:root:Sending error: 501 HTTP request doi not recognized`

This is the simplest way to do it. If now we want a per-module level and naming (i.e class name instead of `root`), I can do it too but that would require more code. And, more code = more bugs.

### CODE REVIEW

**Comment by keomabrun** [comment]
@mitra42  I'll wait for your reply. If you approve this, I will implement it through all the files.

**Comment by mitra42** [comment]
Hi - that looks good, but I remember the hard part of logger is the configuration files, which I don't see. 

My other question, is that I use the verbose=true in the URL as a way to get more debugging on specific queries, which is really helpful when trying to debug something on a live server, i.e. can see more about the query that is typically failing. I notice you took this parameter out, was there a reason for this? i.e. do we need:  if verbose: logging.debug(xxx); or is the verbose flag used to set the configuration somewhere.

note - I'm offline intermittently today, and then fully till Sunday night.

**Comment by keomabrun** [comment]
That's the point. A logger file would allow a more modular (i.e per class) logging configuration. I can set this up, but I want to make sure we really need. Per experience, we usually don't and then we have to struggle with that complicated logging configuration file if we want to modify it.

Regarding the verbose mode, I was thinking about changing the logging level if that argument was passed. ie one time: `if verbose=true: setLoggerLevel(DEBUG)` otherwise the default log level value.
But that would apply to all the future queries unless we change the level back after each query.

**Comment by mitra42** [comment]
Ok - now I'm confused, so without a logger file, where is this being logged? Doesn't the logger file give the file location for example? 

Turning debugging on and off would be ok - but not sure how I'd set that up (compared to adding verbose=true to the call.
I guess setLoggerLevel(DEBUG) could be done in ServerBase._dispatch, around line 104 we know kwargs so can check kwargs.get("verbose") and set there, and then reset after it returns from the call in res = func(*args, **kwargs)

**Comment by keomabrun** [comment]
Can you tell me more about that verbose feature ? Is it for the client to get more results ? Or is it for debug purpose at the server ? If it is for the second reason, I don't see why we put that parameter in the url (initiated by the client). I would rather have a setting in the server side.

This one line gives the logger all the information it needs (end of `ServerGateway.py`):
`logging.basicConfig(filename='dweb_gateway.log', level=logging.DEBUG)`
For simple debugging purposes, and I guess that's what we want, this only line is sufficient.

**Comment by mitra42** [comment]
It's so we can get more debugging info on server for specific queries i.e. It's not a general flag for all queries.

**Comment by keomabrun** [comment]
Alright. I guess it's better to go for `if verbose: logging.debug(xxx);` then.

**Comment by mitra42** [comment]
Agreed

**Comment by keomabrun** [comment]
@mitra42, the branch is ready for reviews. I replaced the print with logging commands.

**Comment by mitra42** [comment]
Thanks Keoma - I merged and deployed.
Note the .format(x,y) I don't believe is generally needed - logging automatically passes arguments to format, but i left as you did them which should also work fine..

**Comment by keomabrun** [comment]
Thank you for merging !
I had some errors when using the logging function with multiple arguments. If we want to do so, we should use the following format: `logging.warning("Protocol problem: %s", "connection reset")`
By (small) experience I find the `.format()` function more robust and it seem to be more consistent between Python 2 and 3.

#### References
https://docs.python.org/2/library/logging.html#logging.debug
https://stackoverflow.com/questions/12382719/python-way-of-printing-with-format-or-percent-form#12382738

**Pull request merged**
